### ISSUE TITLE
Is it possible to embed ConfigEntry entries?

### ISSUE THREAD

**Issue by mrigesh** [rookie-ninja/rk-entry#70]
Assuming that I have the following ConfigEntry entries defined in `boot.yaml`, would it be possible to pass a flag, eg, `embed:true` so that the config entries can be embedded. 

```
config:
    - name: config1
      path: "/some/directory/config1.yaml"
    - name: config2
      content:
          a: b
          c: d
```

Can this section have `embed` as a flag such that the configuration would look like below and the configuration is embedded depending on the value of the flag. 
```
config:
    - name: config1
      path: "/some/directory/config1.yaml"
      embed: true
    - name: config2
      content:
          a: b
          c: d
      embed: true
```

Going through the code, I can see that there already exists a Method to set and get embedded configurations, but that has to be done manually out of the ConfigEntry scope, I hope I'm not wrong here.

The end goal here would be where `rkentry.GlobalAppCtx.GetConfigEntry(name)`, given name=config1 and config1 being embedded, we would be able to fetch the configuration from the same method.
